### ISSUE TITLE
How can i decompile encrypted pyc files with key?

### ISSUE THREAD

**Issue by Numenorean** [extremecoders-re/pyinstxtractor#14]
I have a key, but it seems that pyinstxtractor doesn't support it yet. Will it be created in future updates?

**Comment by extremecoders-re** [comment]
This has been described in the [FAQs](https://github.com/extremecoders-re/pyinstxtractor/wiki/Frequently-Asked-Questions#decrypting-pyinstaller--40).

**Comment by Numenorean** [comment]
> This has been described in the [FAQs](https://github.com/extremecoders-re/pyinstxtractor/wiki/Frequently-Asked-Questions#decrypting-pyinstaller--40).

thanks, will be this implemented directly in pyinstxtractor.py?

**Comment by extremecoders-re** [comment]
At the moment there are no plans to directly integrate it within pyinstxtractor but may be in the form of a helper script.
