### ISSUE TITLE
python 3.9.x not work

### ISSUE THREAD

**Issue by levanhau03** [extremecoders-re/pyinstxtractor#15]
please add support python 3.9.x

**Comment by extremecoders-re** [comment]
Hi, Python 3.9 is already supported.
Test binaries: https://github.com/extremecoders-re/pyinstxtractor-test-binaries

**Comment by levanhau03** [comment]
pydata.zip
<https://drive.google.com/file/d/1AG4RxplR53933ugiBcjpRas3_yUWAGb6/view?usp=drive_web>
Error: Failed to decompress PYZ-00.pyz_extracted
this version 3.8

Vào Th 4, 7 thg 4, 2021 vào lúc 18:15 Rom Builder ***@***.***>
đã viết:

**Comment by extremecoders-re** [comment]
This has been generated with Python 3.8. Pyinstxtractor works fine.

```
λ python pyinstxtractor.py pydata.dump
[+] Processing pydata.dump
[+] Pyinstaller version: 2.1+
[+] Python version: 38
[+] Length of package: 8662397 bytes
[+] Found 53 files in CArchive
[+] Beginning extraction...please standby
[+] Possible entry point: pyiboot01_bootstrap.pyc
[+] Possible entry point: pyi_rth_multiprocessing.pyc
[+] Possible entry point: dna.pyc
[+] Found 267 files in PYZ archive
[!] Error: Failed to decompress PYZ-00.pyz_extracted\__future__.pyc, probably encrypted. Extracting as is.
[!] Error: Failed to decompress PYZ-00.pyz_extracted\_compat_pickle.pyc, probably encrypted. Extracting as is.
[!] Error: Failed to decompress PYZ-00.pyz_extracted\_compression.pyc, probably encrypted. Extracting as is.
```

Additional note: The pyc's inside the pyz are encrypted so you need to decrypt them further as described in the Wiki. Encryption key is `HptrjfgxDNA20210`

**Comment by levanhau03** [comment]
I know, can you add a key to the app ?

Vào Th 5, 8 thg 4, 2021 vào lúc 02:19 extremecoders-re <
***@***.***> đã viết:

**Comment by extremecoders-re** [comment]
It's mentioned here.

https://github.com/extremecoders-re/pyinstxtractor/wiki/Frequently-Asked-Questions#decrypting-pyinstaller--40

**Comment by extremecoders-re** [comment]
Closing. Feel free to repoen if there're any more questions.
