### ISSUE TITLE
Deparsing stopped due to parse error

### ISSUE THREAD

**Issue by ildan-gh** [extremecoders-re/pyinstxtractor#17]
Hi there, thanks for your work.

`Deparsing stopped due to parse error`

I'm getting this error when trying to decode an .exe file via uncompyle6. What causes this issue?
I have uploaded the zip file here if you want to have a look: https://www.dropbox.com/s/rr8e3n9p7ta0ya9/LS.zip?dl=0

Installed python version: 3.8.0
OS: Windows 10

**Comment by extremecoders-re** [comment]
The error is due to uncompyle6. You can try the other decompiler (https://github.com/rocky/python-decompile3) but nothing much can be done about it. You can ofcourse try disassembling instead to make sense of the code.
