### ISSUE TITLE
extract failed

### ISSUE THREAD

**Issue by MlgmXyysd** [extremecoders-re/pyinstxtractor#20]
```
> python pyinstxtractor.py linux_x64
[+] Processing linux_x64
[+] Pyinstaller version: 2.1+
[+] Python version: 27
[+] Length of package: 55915 bytes
Traceback (most recent call last):
  File "pyinstxtractor.py", line 390, in <module>
    main()
  File "pyinstxtractor.py", line 378, in main
    arch.parseTOC()
  File "pyinstxtractor.py", line 210, in parseTOC
    self.fPtr.read(entrySize - 4))
struct.error: unpack requires a string argument of length 576508212
```

The binary may have been confusion

[linux_x64.zip](https://github.com/extremecoders-re/pyinstxtractor/files/6730013/linux_x64.zip)

**Comment by extremecoders-re** [comment]
The binary has been compiled with a modded version of pyinstaller. Several parts of the pyz data are xor encrypted. To extract this you need to reverse engineer the bootloader and see how it differs from the standard one. 

For example, this is the XOR decryption loop. Standard pyinstaller has no such thing.

![image](https://user-images.githubusercontent.com/12072382/124113645-4badfb00-da89-11eb-8c69-b9e317650966.png)
