### ISSUE TITLE
use pyinstaller 4.3 and python 3.7 to build hello exectuable  app,but pyinstxtractor extract failed

### ISSUE THREAD

**Issue by duanshuaimin** [extremecoders-re/pyinstxtractor#21]
output message:[!] Error : Unsupported pyinstaller version or not a pyinstaller archive ,does pyinstractor support 4.3?

**Comment by extremecoders-re** [comment]
Pyinstxtractor does support PyInstaller 4.3 exe's. Linux ELFs are also supported, more details in the Wiki.
