### ISSUE TITLE
The behavior of finding magic pattern didn't match the original one.

### ISSUE THREAD

**Issue by Ai-Himmel** [extremecoders-re/pyinstxtractor#25]
According to the [source code](https://github.com/pyinstaller/pyinstaller/blob/57311bdd0c41529c055bf39e22d63e99af717aad/bootloader/src/pyi_archive.c#L366:1) of pyinstaller, the bootloader find the MAGIC pattren by searching from end to front but not the fixed end-of-file offset.

**Comment by extremecoders-re** [comment]
Resolved in latest commit as described in #26
