### ISSUE TITLE
HELP me pls with cookie

### ISSUE THREAD

**Issue by snow0x** [extremecoders-re/pyinstxtractor#27]
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

help meee :))

**Comment by extremecoders-re** [comment]
Can you post a hexdump of the last few bytes of the file? Or you can upload it here if it's not copyrighted.

**Comment by ElieenAndBella** [comment]
Do you fix it? I have this problem too.

**Comment by bigblackhat** [comment]
你好，我也出现了该问题
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

**Comment by MarkThe** [comment]
No did not fixed

**Comment by abitgen** [comment]
How to provide the hexdump of last few bytes of 
the file?

**Comment by extremecoders-re** [comment]
@abitgen 
On Linux, run `xxd <file> | tail`, post a screenshot

On Windows, open the file in a hex editor  (eg HxD), navigate to the end of the file and post a screenshot,

**Comment by abitgen** [comment]
This is the exe file's hex dump

```
00dd08f0: 5e7c f1ee 3c21 b6cf 6bf2 74ce 5cae 2e1c  ^|..<!..k.t.\...
00dd0900: f028 a2c5 8260 26f3 d119 f3b9 26d9 011e  .(...`&.....&...
00dd0910: 25b5 79c5 4ad2 9da4 47df 3c9f 93ef d341  %.y.J...G.<....A
00dd0920: 5865 64ec 4146 89ef 2e42 e59d 4908 7629  Xed.AF...B..I.v)
00dd0930: 3c68 bf66 89b1 eb9e d75d 6e3f 31d0 fede  <h.f.....]n?1...
00dd0940: 6b3d 020e 66eb 03af 879c f0ff 3292 0d9f  k=..f.......2...
00dd0950: 6573 3fe0 3a22 8606 424a 26a6 cd49 2e61  es?.:"..BJ&..I.a
00dd0960: cdf3 48e0 6d02 e077 a740 703b c07d b8a7  ..H.m..w.@p;.}..
00dd0970: 7bf1 3c32 f87e 1a18 ff82 4e17 df3f b315  {.<2.~....N..?..
00dd0980: 760d 0000 0000 0000 88db d600 0000 0000  v...............
```

**Comment by extremecoders-re** [comment]
@abitgen Judging from the hex dump, it doesn't look like a standard pyinstaller executable.
