### ISSUE TITLE
I have error with pyinstxtractor

### ISSUE THREAD

**Issue by MarkThe** [extremecoders-re/pyinstxtractor#29]
The problem is that when i trying to extract exe gives error 
Evey time
Im on kali linux 
Is there any missing commands to do 
Requirements ??

**Comment by MarkThe** [comment]
Ive installed uncolpe 6 and pyinstaller

**Comment by extremecoders-re** [comment]
Attach the exe and I can take a look.

**Comment by MarkThe** [comment]
@extremecoders-re im decopile 
![image](https://user-images.githubusercontent.com/81533176/147849815-ba5b7951-f170-47e9-972a-a18d30e5f073.png)

a virus

**Comment by MarkThe** [comment]
it was working before ive resetted my kali machine

**Comment by MarkThe** [comment]
@extremecoders-re 
can u answer on me

**Comment by extremecoders-re** [comment]
@MarkThe May be you're not using the latest version of pyinstxtractor.

**Comment by MarkThe** [comment]
no i have using latest and not working still missing cookies and not working i have tryed unnistall and install but it didnot work so any help @extremecoders-re

**Comment by extremecoders-re** [comment]
@MarkThe I can check if you attach the exe here.

**Comment by MarkThe** [comment]
@extremecoders-re TAKE CARE ITS A VIRUS IN PY

**Comment by MarkThe** [comment]
@extremecoders-re https://www.mediafire.com/file/3j2c8o79ezq64q7/full+pubg+hack+for+streamer.rar/file

**Comment by MarkThe** [comment]
also i need to fix my problem that i cannot use it anymore on kali linux

**Comment by pp0236** [comment]
> @extremecoders-re https://www.mediafire.com/file/3j2c8o79ezq64q7/full+pubg+hack+for+streamer.rar/file

work fine for me
![image](https://user-images.githubusercontent.com/54238880/156880637-f10f2704-f824-4eb9-8011-02926b3b83a1.png)

maybe kali incompatibility with script?

**Comment by extremecoders-re** [comment]
@MarkThe Check the version of Python installed in Kali. Extracting this exe requires Python 3.10.

**Comment by MarkThe** [comment]
dankeschön it works now i have uninstalled kali and reinstall and it works finally thanks @extremecoders-re @pp0236 thank u both
