### ISSUE TITLE
Nothing can saw after running command

### ISSUE THREAD

**Issue by Boliang-Lu** [extremecoders-re/pyinstxtractor#3]
![image](https://user-images.githubusercontent.com/32253349/86095276-4586e680-bae4-11ea-8a58-796b613897cc.png)
![image](https://user-images.githubusercontent.com/32253349/86095288-4a4b9a80-bae4-11ea-885f-b8b3a22a5792.png)

**Comment by extremecoders-re** [comment]
Hmm, that's weird.

What's the output of the following commands? Do they print anything at all.

```
python pyinstxtractor.py
python pyinstxtractor.py nonexistentfile.exe
```

Also what is the version of Python you are using?

**Comment by Boliang-Lu** [comment]
I solved
` py pyinstxtractor.py nonexistentfile.exe`
thanks
