### ISSUE TITLE
cant decompile

### ISSUE THREAD

**Issue by isiikz** [extremecoders-re/pyinstxtractor#31]
[+] Processing gen.exe
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

when i try with unpy2exe it say its a pyinstaller so im out of idea

**Comment by extremecoders-re** [comment]
It may be a modified pyinstaller exe. You can attach the exe and I can take a look.

**Comment by isiikz** [comment]
here the exe in a zip file since github doesnt allow exe to be post

**Comment by isiikz** [comment]
here the exe in a zip file since github doesnt allow exe to be post 

https://www.mediafire.com/file/z15aap8fc0ihsdl/test.zip/file

**Comment by extremecoders-re** [comment]
This is not pyinstaller exe. This has been compiled by Nuitka.
