### ISSUE TITLE
Can't decompile

### ISSUE THREAD

**Issue by Pylonium** [extremecoders-re/pyinstxtractor#32]
I tried to decompile a exe via pyinstxtractor but it resulted in an error.

If you want to take a look at it here is the file:

https://www.mediafire.com/file/1mdv3imid2bxskd/Wanting_to_decompile.exe/file

**Comment by Pylonium** [comment]
Note: You also need this file
https://www.mediafire.com/file/ofv8cywq6sz9aka/Config.json/file

**Comment by extremecoders-re** [comment]
This is not pyinstaller exe. This has been compiled by Nuitka.

**Comment by Pylonium** [comment]
Alright thanks for trying :)
