### ISSUE TITLE
Create release / tag on github

### ISSUE THREAD

**Issue by dmknght** [extremecoders-re/pyinstxtractor#35]
Hello! I'm package maintainer of Parrot OS and I want to create a Debian package of your tool on our repository. To make Debian package, it is easier for us if you have releases / tags that have source code in tarball files. So we can update newer version with uscan easily.

**Comment by extremecoders-re** [comment]
Hi, this has been done :)

**Comment by dmknght** [comment]
> Hi, this has been done :)

Hello! Thank you very much. I'm wondering if you can change the tag name prefix a little bit? For example Dec-2021 goes to 2021.12. It will be perfect.

**Comment by extremecoders-re** [comment]
@dmknght Changed the tag name to "2021.12". Thank you!

**Comment by dmknght** [comment]
> @dmknght Changed the tag name to "2021.12". Thank you!

Thank you very much! I'm on it. I guess I can close this issue now :D
