### ISSUE TITLE
Error : Missing cookie - Need file detection

### ISSUE THREAD

**Issue by Commifreak** [extremecoders-re/pyinstxtractor#36]
Sorry to bother you with basic things - but I assume the attached exe should be packed with pyinstaller - but the xtractor does not accept it.

Could you take a closer look?

```
python pyinstxtractor.py app.exe
[+] Processing app.exe
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive
```

https://www.mediafire.com/file/mg5dgslaiatp0o3/app.exe/file

Or is kind ob obfuscated to trick the xtractor?

**Comment by Commifreak** [comment]
After some more playing - its seems, that this is a nuitka generated exe.

**Comment by extremecoders-re** [comment]
It's Nuitka indeed.
