### ISSUE TITLE
The correct Python version was not obtained

### ISSUE THREAD

**Issue by Curtion** [extremecoders-re/pyinstxtractor#37]
use python 3.6.0 version, `self.pyver` value is `306`,  This causes to add the wrong magic number

**Comment by ncaklovic** [comment]
True for all newer Python versions (they were preparing for 3.10, 3.11), something like this pseudocode can be used:

```
        n = pyver > 100 ? 100 : 10;
        major = pyver / n;
        minor = pyver % n;
```
