### ISSUE TITLE
Cannot get pyinstxtractor to work

### ISSUE THREAD

**Issue by Ixonblitz-MatOS** [extremecoders-re/pyinstxtractor#38]
I have an exe that was formatted in pyinstaller 4.9 and need it to be decompiled and it is saying that I cannot because of version or mising cookie

**Comment by extremecoders-re** [comment]
Just tested with pyinstaller 4.9 and the script is working fine. Would be able to help if you can attach the exe.

**Comment by Ixonblitz-MatOS** [comment]
Okay I'll do that as soon as possible.
