### ISSUE TITLE
Modified pyinstaller

### ISSUE THREAD

**Issue by Amoled** [extremecoders-re/pyinstxtractor#39]
Hello!

I have modified pyinstaller ELF. Can you take a look please?
Thanks!

https://1drv.ms/u/s!AhPkgOPZ3CoFgbNCKsqJ08aaNjBlPg?e=hWQGtt

**Comment by extremecoders-re** [comment]
This is similar to this issue: https://github.com/extremecoders-re/pyinstxtractor/issues/20#issuecomment-872139286

Parts of the pyinstaller structures are xor encrypted.
![image](https://user-images.githubusercontent.com/12072382/156874226-036d6141-df69-4153-b939-705161af1e87.png)

**Comment by Amoled** [comment]
Maybe you can give examples of how to modify the pyinstxtractor code to support this modification? Thanks!

**Comment by fahadbashirgg** [comment]
@Amoled hello bro can you Give me this moded version let me check it...?
