### ISSUE TITLE
Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by userxxx0** [extremecoders-re/pyinstxtractor#40]
Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

**Comment by extremecoders-re** [comment]
Difficult to help without more details, specifically the file in question.

**Comment by Clove-MJC** [comment]
Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

**Comment by FLUORESCENTXX** [comment]
pip install pyinstaller on CMD as admin

**Comment by Clove-MJC** [comment]
what??&nbsp;I want to crack it, but it's protected




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月22日(星期五) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [extremecoders-re/pyinstxtractor] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive (Issue #40)





 
pip install pyinstaller on CMD as admin

**Comment by euclidsss** [comment]
it means it wasnt compiled in pyinstaller... your not a good reverse engineer if you dont understand that

**Comment by Clove-MJC** [comment]
lol.i know 。I mean, can you crack this program。I am willing to pay



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月26日(星期二) 晚上6:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [extremecoders-re/pyinstxtractor] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive (Issue #40)





 
it means it wasnt compiled in pyinstaller... your not a good reverse engineer if you dont understand that
