### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Sheelia** [extremecoders-re/pyinstxtractor#41]
![Ekran Alıntısı](https://user-images.githubusercontent.com/85132999/159356952-7fb6ee2a-4e1d-4099-924d-7d791f3a9064.PNG)

**Comment by extremecoders-re** [comment]
Pyinstxtractor must be run in the same version of Python which was used to build the executable.
In your case, try with Python 3.10 as suggested.

**Comment by euclidsss** [comment]
skid
