### ISSUE TITLE
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by ashclapz** [extremecoders-re/pyinstxtractor#43]
im having a error [!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive does anyone have  a fix for this?

**Comment by extremecoders-re** [comment]
Can take a look if you attach the file in question.

**Comment by ashclapz** [comment]
sure 
![image](https://user-images.githubusercontent.com/80973355/167269368-2a38011d-0c08-4d77-8790-ecfdb7a6aea1.png)

**Comment by extremecoders-re** [comment]
Hi, there can be many reasons. The screenshot is not enough to know why it didn't work. Quite possible that its using a modified/custom pyinstaller.

**Comment by ashclapz** [comment]
basically im trying to get the source code of this file C:\Users\user\AppData\Roaming\Python\Python310\Scripts\pyinstaller.exe 
the src of pyinstaller and whenever i use pyinstxtractor.py it wont work

**Comment by extremecoders-re** [comment]
EXE files in "Python/scripts" aren't pyinstaller executables in general. They are script wrappers generated by setuptools and the likes during installation of a Python package.

**Comment by ashclapz** [comment]
nvm i fixed it

**Comment by yxh6067** [comment]
@ashclapz how do you do
