### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'pyd-runtime-tmpdir C:'

### ISSUE THREAD

**Issue by nevarDeath** [extremecoders-re/pyinstxtractor#44]
Error is in the title. I have python 3.8.0 installed. pyinstxtractor says the python version of my file is 38. It also says pyinstaller version is 2.1+ I've also independently verified this exe was packaged by pyinstaller. I'm running the following command in an admin command shell in Win10:

`python pyinstxtractor.py program.exe`

Here is the traceback info:
![image](https://user-images.githubusercontent.com/105323447/167730591-74c1fe19-3129-41d1-9ab8-08f8bdc62b29.png)

Is it possible this is due to something the developer of the packaged script did in their file(s) or is this something on my end/pyinstxtractor?

**Comment by extremecoders-re** [comment]
Please check with the latest commit.

**Comment by nevarDeath** [comment]
Thank you! I did use the script from your newest commit, but it now encounters the same problem at different line numbers. I'm running this on a windows 10 VM, so still running in the exact same environment described in the original post. Here's the traceback with the newest commit:

![traceback](https://user-images.githubusercontent.com/105323447/168140369-4cac64f5-9b58-46d7-b29e-f073c51699e3.png)

**Comment by extremecoders-re** [comment]
Have reordered the if statements. Please check once again with the attached file.

[pyinstxtractor.py](https://github.com/extremecoders-re/pyinstxtractor/files/8681858/pyinstxtractor.py.txt)

**Comment by nevarDeath** [comment]
That resolved it, thank you so much!
![image](https://user-images.githubusercontent.com/105323447/168177210-755f3806-ea01-421c-80fc-aeb1b0847fa7.png)

**Comment by extremecoders-re** [comment]
Thanks for testing! 👍
