### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Jodank** [extremecoders-re/pyinstxtractor#46]
Hi!
I got this error when I try to use this extractor:

**E:\Temp\test>python.exe pyinstxtractor.py Cookie test.exe
  File "pyinstxtractor.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax**

**Comment by extremecoders-re** [comment]
Line 8 is within a comment.

https://github.com/extremecoders-re/pyinstxtractor/blob/4dc147a37939b744a1586064193af92ffab37675/pyinstxtractor.py#L6-L9

Please check if you have downloaded the file correctly.
