### ISSUE TITLE
ValueError: read length must be positive or -1

### ISSUE THREAD

**Issue by frakman1** [extremecoders-re/pyinstxtractor#47]
When used on a Mac binary, I get this error.
High Sierra 10.13.6

```python3
~/.pyenv/shims/python3 pyinstxtractor.py ./lights.app/Contents/MacOS/lights
[+] Processing ./lights.app/Contents/MacOS/lights
[+] Pyinstaller version: 2.0
[+] Python version: 36
[+] Length of package: 6690129 bytes
Traceback (most recent call last):
  File "pyinstxtractor.py", line 423, in <module>
    main()
  File "pyinstxtractor.py", line 411, in main
    arch.parseTOC()
  File "pyinstxtractor.py", line 237, in parseTOC
    self.fPtr.read(entrySize - 4))
ValueError: read length must be positive or -1

$~/.pyenv/shims/python3 --version
Python 3.6.5

```

**Comment by extremecoders-re** [comment]
Can you share the file?

**Comment by frakman1** [comment]
[lights.zip](https://github.com/extremecoders-re/pyinstxtractor/files/8838183/lights.zip)
Unzip to get the file.

**Comment by extremecoders-re** [comment]
For the moment you can use an older version of pyinstxtractor.

This one works fine:
https://raw.githubusercontent.com/extremecoders-re/pyinstxtractor/cc69ba88bb714dd857a2bacbf8d0df3550849f96/pyinstxtractor.py

**Comment by extremecoders-re** [comment]
The bug has been fixed now. So you can use the latest commit.

**Comment by frakman1** [comment]
Confirmed that latest version works. Thank you!
