### ISSUE TITLE
extraction fails with executable made with --onefile option.

### ISSUE THREAD

**Issue by uwuplant** [extremecoders-re/pyinstxtractor#48]
first of all - thank you for this amazing tool!

script fails to extract anything from [this executable (MALICIOUS)](https://transfer.sh/8WT24L/kekw), seemingly because it was compiled using the [--onefile](https://pyinstaller.org/en/stable/usage.html#cmdoption-F) option. when run, it throws the following error. 
`[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive`

if this is just user error on my end, then I'm sorry :/

**Comment by extremecoders-re** [comment]
No worries.

This is a [nuitka](https://github.com/Nuitka/Nuitka) generated exe. Not pyinstaller

```
$ strings kekw | grep -i nuitka
NUITKA_ONEFILE_PARENT
```

**Comment by uwuplant** [comment]
ah, that explains it. thank you!
