### ISSUE TITLE
cant decompile

### ISSUE THREAD

**Issue by Disturbies** [extremecoders-re/pyinstxtractor#52]
with open(filename, 'wb+') as pycFile:
ValueError: embedded null character

**Comment by Disturbies** [comment]
Full log:
[+] Processing madclips.exe
[+] Pyinstaller version: 2.1+
[+] Python version: 3.10
[+] Length of package: 8420072 bytes
[+] Found 38 files in CArchive
[+] Beginning extraction...please standby
[+] Possible entry point: pyiboot01_bootstrap.pyc
[+] Possible entry point: pyi_rth_inspect.pyc
[+] Possible entry point: pyi_rth_subprocess.pyc
[+] Possible entry point: pyi_rth_pkgutil.pyc
[+] Possible entry point: pyi_rth_multiprocessing.pyc
[+] Possible entry point: pyimod04_certifi     . 0.pyc
Traceback (most recent call last):
  File "F:\Рабочий стол\Projects\reverse\MadClips\pyinstxtractor.py", line 424, in <module>
    main()
  File "F:\Рабочий стол\Projects\reverse\MadClips\pyinstxtractor.py", line 413, in main
    arch.extractFiles()
  File "F:\Рабочий стол\Projects\reverse\MadClips\pyinstxtractor.py", line 304, in extractFiles
    self._writePyc(entry.name + '.pyc', data)
  File "F:\Рабочий стол\Projects\reverse\MadClips\pyinstxtractor.py", line 320, in _writePyc
    with open(filename, 'wb+') as pycFile:
ValueError: embedded null character

**Comment by Disturbies** [comment]
My working crutch, most likely you can do a more spot check and more universal names, but the main thing is that it worked for me

if filename.startswith("pyimod04_certifi"):
      filename = "pyimod04_certifi"

**Comment by Disturbies** [comment]
My working crutch, most likely you can do a more spot check and more universal names, but the main thing is that it worked for me
![carbon](https://user-images.githubusercontent.com/60567807/178862000-f7731293-2db9-4439-95d2-9e08f341692c.png)

**Comment by extremecoders-re** [comment]
Thanks for the report.

Probably something like this should also work to remove trailing nulls
```python
with open(filename.strip(), 'wb+') as pycFile:
```
