### ISSUE TITLE
PYZ file didnt extract

### ISSUE THREAD

**Issue by combo23** [extremecoders-re/pyinstxtractor#57]
I used the script to some exe but the "PYZ-00.pyz_extracted" folder is empty and i dont really know what to do about it

**Comment by extremecoders-re** [comment]
Please attach the exe file or share a link and I can take a look.

**Comment by extremecoders-re** [comment]
Please make sure you're using the same version of Python as the one used to build the executable. Running pyinstxtractor in a different version of Python would skip pyz extraction.

Alternatively try pyinstxtractor-ng: https://github.com/pyinstxtractor/pyinstxtractor-ng
It's a standalone tool and doesn't require even a Python installation.

**Comment by combo23** [comment]
just tried the -ng version and it worked perfectly so i am guessing i did have different py version, thanks for help
