### ISSUE TITLE
Missing encrypted files after successful extract 

### ISSUE THREAD

**Issue by UltraV8** [extremecoders-re/pyinstxtractor#58]
I’m trying to extract a PYZ that I know it should contains *.pyc.encrypted files. The extraction finished without any errors but those files are missing, what could be the reason for that?

**Comment by extremecoders-re** [comment]
There should be a pyz file within the extracted directory. What's the size of that file?

**Comment by UltraV8** [comment]
It’s about 12M

**Comment by extremecoders-re** [comment]
Please make sure you're using the same version of Python as the one used to build the executable. Running pyinstxtractor in a different version of Python would skip pyz extraction.

Alternatively try pyinstxtractor-ng: https://github.com/pyinstxtractor/pyinstxtractor-ng
It's a standalone tool and doesn't require even a Python installation.

**Comment by extremecoders-re** [comment]
Loading at runtime doesn't matter. If the pyz is there it should be extracted, unless its a modified installer bootloader.
