### ISSUE TITLE
Not working on 4.0

### ISSUE THREAD

**Issue by raifpy** [extremecoders-re/pyinstxtractor#6]
[!] Error : Unsupported pyinstaller version or not a pyinstaller archive

>> pyinstaller --version
4.0
>>

**Comment by extremecoders-re** [comment]
Hi, just tested the script on an exe generated by PyInstaller 4.0 and it's working fine. If it's really a PyInstaller exe, check whether it is signed. Signed exe's are not supported. Check the FAQ for more details.

[Test exe](https://github.com/extremecoders-re/pyinstxtractor-test-binaries/blob/master/python3.8-pyinstaller4.0.exe)
