### ISSUE TITLE
Can you tell me how to run this?

### ISSUE THREAD

**Issue by Akhilnandh** [extremecoders-re/pyinstxtractor#65]
Hello,

I am trying to convert a .exe file for which the .py file was accidentally deleted before commiting onto git.
?
Would some one be able to let me know how to go about using this tool

**Comment by pp0236** [comment]
see [example](https://github.com/extremecoders-re/pyinstxtractor#example)

**Comment by extremecoders-re** [comment]
Please follow the example usage as mentioned above. This requires to run pyinstxtractor using the same version of Python as the exe. Next you run a decompiler on the produced pyc files to get back the py files. However do not the decompilation support for current versions of Python (anything above 3.7) is not good enough at the moment. In that case you can resort to manual decompilation by hand which does take a lot of time but doable.
