### ISSUE TITLE
How to patch a .pyc file in existing pyinstaller build?

### ISSUE THREAD

**Issue by brappier** [extremecoders-re/pyinstxtractor#74]
I wanted to see if i can update a .pyc file in a build. It looks like I have to go through the TOC and then find the PYZ-00.pyz . Then extract PYZ-00.pyz, and recompress it.
Will that violate any checksums or anything?
Assuming the new .pyz will have a different size? what other values do i have to patch in the binary?

**Comment by brappier** [comment]
https://github.com/extremecoders-re/pyinstxtractor/wiki/Replacing-files-inside-the-CArchive 

In this article, the new file has to be less than the old one. 
what to do if the new file is more in size??

**Comment by extremecoders-re** [comment]
> Will that violate any checksums or anything?

There no checksums used anywhere in pyinstaller.


> In this article, the new file has to be less than the old one.
> what to do if the new file is more in size??

If the new file is larger in size than the older it implies all other files which are located after that file have to be shifted. As a result, the table of contents of the CArchive has to be updated with the new offsets for all the affected files.

**Comment by brappier** [comment]
Yes, I shifted everything properly and I updated the TOC also the Cookie.

The patched program does not execute properly. I get `killed` as soon as i run the program. 
The thing is that the position of the cookie is also updated, but I dont know there the offset of the cookie is stored, so that is not updated, hence maybe that is why it does not execute. 

As a sanity check i ran pyinstxtractor.py on the pathced file, and it is able to extract everything without any error. so i have updated all offsets etc ( which are mentioned in your script ) properly. 

Also, I am on a mac.

**Comment by brappier** [comment]
I think there is  some content in the tail which has to be updated, idk what all though.

**Comment by extremecoders-re** [comment]
I see. Mac is tricky. If you go through the pyinstaller source, it requires signing the executable. The modifications invalidates the signature and could be the reason why the process gets killed immediately.

https://github.com/pyinstaller/pyinstaller/blob/779a94968ecc55e0cc23ea89cb3b6523e7cff576/PyInstaller/building/api.py#L785-L806

https://github.com/pyinstaller/pyinstaller/blob/779a94968ecc55e0cc23ea89cb3b6523e7cff576/PyInstaller/building/api.py#L822-L845

**Comment by brappier** [comment]
Yup, unsigning it, then patching it and signing it again works. Thanks.
Whats surprising is that you dont have to do that if the payload is smaller in size.
