### ISSUE TITLE
Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by PotatoMand123** [extremecoders-re/pyinstxtractor#75]
Hello when i try to pyinstxtractor it keep saying Missing cookie, unsupported pyinstaller version or not a pyinstaller archive
I just updated pip and pyinstaller can you please help`?
![image](https://github.com/extremecoders-re/pyinstxtractor/assets/142716642/e533c666-1d09-465e-a42c-e099c36aba64)

**Comment by extremecoders-re** [comment]
It could be a modified pyinstaller executable. Need to look at the binary first.

**Comment by PotatoMand123** [comment]
Can you add me on discord ? my account briannysccount

Bc idk were i can show it

**Comment by extremecoders-re** [comment]
You can upload the file somewhere and share the link here. If not possible, discord is fine.

**Comment by PotatoMand123** [comment]
I cant find it could you add me?

brianbackupppp

**Comment by PIRMANGANS** [comment]
> Hello when I try pyinstxttractor it keeps saying Cookie missing, pyinstaller version not supported or not pyinstaller archive I just updated pip and pyinstaller can you help`? ![image](https://user-images.githubusercontent.com/142716642/261840489-e533c666-1d09-465e-a42c-e099c36aba64.png)
I'm also getting the same error, is there a way to fix it?

**Comment by PureWaterSun** [comment]
![image](https://github.com/extremecoders-re/pyinstxtractor/assets/42731510/d4eb54eb-f97d-4cd0-a540-06487367d900)
I'm also getting the same error, how to solve it

**Comment by extremecoders-re** [comment]
> I'm also getting the same error, how to solve it

I can take a look if you upload the binary somewhere and share a link.

**Comment by PureWaterSun** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到！

**Comment by PureWaterSun** [comment]
这是来自QQ邮箱的自动回复邮件。
 已收到！
