### ISSUE TITLE
Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by walmart44** [extremecoders-re/pyinstxtractor#77]
exe file: https://www.mediafire.com/file/9a0jqtnq0mxdn0m/main.exe/file

**Comment by extremecoders-re** [comment]
Link does not work, is blocked.

**Comment by walmart44** [comment]
> Link does not work, is blocked.

https://drive.google.com/file/d/1MpshCnh-_KFPOGjn56Usq49qXtWHcpfB/view?usp=sharing

**Comment by extremecoders-re** [comment]
> https://drive.google.com/file/d/1MpshCnh-_KFPOGjn56Usq49qXtWHcpfB/view?usp=sharing

Same with Google Drive. Not accessible.

> We're sorry. You can't access this item because it is in violation of our Terms of Service.

**Comment by walmart44** [comment]
> > https://drive.google.com/file/d/1MpshCnh-_KFPOGjn56Usq49qXtWHcpfB/view?usp=sharing
> 
> Same with Google Drive. Not accessible.
> 
> > We're sorry. You can't access this item because it is in violation of our Terms of Service.

Do you have a discord or something I can send it to?

**Comment by extremecoders-re** [comment]
Put it in a password protected zip, use any file sharing service, then share the link along with the password here.

- https://gofile.io/
- https://krakenfiles.com/
- https://pixeldrain.com/
- https://anonymfile.com/

**Comment by walmart44** [comment]
https://gofile.io/d/eq8A9U

**Comment by extremecoders-re** [comment]
This is a nuitka compiled executable. Not pyinstaller. 

The contents of the executable extracted with nuitka-extractor:
https://gofile.io/d/Sp7TGS

There won't be any pyc files regardless

**Comment by walmart44** [comment]
> This is a nuitka compiled executable. Not pyinstaller.
> 
> The contents of the executable extracted with nuitka-extractor: https://gofile.io/d/Sp7TGS
> 
> There won't be any pyc files regardless

So is it possible to decompile it to python?

**Comment by extremecoders-re** [comment]
Nuitka compiles Python bytecode to native code. 
It would be very difficult to reverse native code to high level Python source code.
