### ISSUE TITLE
PYZ-00.pyz cannot decrypt. I have tried many ways, but I cannot extract them

### ISSUE THREAD

**Issue by Pnut-GGG** [extremecoders-re/pyinstxtractor#78]
This is a very interesting pyinstaller package that seems to rewrite some files in Crypto (such as AES, I guess so because there are Crypto's pyd files in the software root directory)

This is the complete installation package of the software
https://pixeldrain.com/u/Ff6FXAQ2
or
https://gofile.io/d/eX5GTn

**Comment by extremecoders-re** [comment]
There are no tricks in that file. Its standard PyInstaller but an old version. There was a bug in pyinstxtractor-ng which was breaking decryption.

This has been fixed in the latest release: https://github.com/pyinstxtractor/pyinstxtractor-ng

**Comment by Pnut-GGG** [comment]
thank you for your reply
