### ISSUE TITLE
Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by Penguinehis** [extremecoders-re/pyinstxtractor#79]
Hi I tryng to discover what type of installer is used in this binary but no luck :/

https://gofile.io/d/jCHlPM

**Comment by extremecoders-re** [comment]
This is nuitka

**Comment by Penguinehis** [comment]
I tryend nuikita same error

**Comment by Penguinehis** [comment]
In the case i receive the Processing sshplus
[+] File type: ELF
[+] Payload size: 0 bytes
[!] Nuitka magic header mismatch

**Comment by Penguinehis** [comment]
> This is nuitka

its possible to debug to find where is the problem with the header?

**Comment by extremecoders-re** [comment]
It does not use onefile mode. There is nothing to extract. 
Its using standalone mode. The other relevant files should already be present in the same directory as sshplus.
