### ISSUE TITLE
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by walmart44** [extremecoders-re/pyinstxtractor#80]
https://gofile.io/d/J6VSOH

**Comment by walmart44** [comment]
its obf but was hoping you'd be able to deobf it

**Comment by extremecoders-re** [comment]
Replace the exec with print. That will print the next stage, repeat this recursively till when you get to the final stage. From there on need AST transformation to simplify.
