### ISSUE TITLE
Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by dIMAtITEN** [extremecoders-re/pyinstxtractor#81]
Hello, why i got error?
Missing cookie, unsupported pyinstaller version or not a pyinstaller archive
python 3.1

https://gofile.io/d/oueY0t

**Comment by extremecoders-re** [comment]
It's a self extracting WinRAR archive. Just use WinRAR or 7zip to extract.

**Comment by dIMAtITEN** [comment]
@extremecoders-re 
[!] Nuitka magic header mismatch

and so, if i delete some dll file i got error:
![image](https://github.com/extremecoders-re/pyinstxtractor/assets/148960641/c98d8f60-89e1-4b8e-8c15-61be03fd81e2)

**Comment by extremecoders-re** [comment]
which dll file did you delete to get that error?
