### ISSUE TITLE
Missing cookie

### ISSUE THREAD

**Issue by scott870430** [extremecoders-re/pyinstxtractor#85]
Hi, I want to decompile a [Python project](https://ufile.io/a079jtfv), but it's giving me the following error: Error: Missing cookie, unsupported PyInstaller version, or not a PyInstaller archive.

I executed the command python pyinstxtractor.py C:\Users\User\Desktop\xxx\bin\main.exe.

I have zero experience with Python packages, and I initially thought that this project was packaged with PyInstaller. However, it seems that might not be the case.

Is there any mistake in my operation? Or perhaps the project is not packaged with PyInstaller? Do you have any suggestions for me on how to successfully decompile the project?

Thank you in advance.

**Comment by extremecoders-re** [comment]
Main.exe is packaged with nuitka.

Nuitka normally doesn't include python bytecode in the executable, instead compiles bytecode to native code. Hence there usually won't be any python code to decompile.

**Comment by scott870430** [comment]
I see. Thank you for your help!
