### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Godisgracious1031** [extremecoders-re/pyinstxtractor#87]
Hi!

I was able to run it, I went into the extracted folder and I tried the commands. It did not work..

Kindly assist!

Here is link to Exe and the folder: 
https://1drv.ms/f/s!AploExad608_h4M4R7mIB-zs2DL7mA?e=cJRY6L

Thanks,

God bless,

Shawn

**Comment by extremecoders-re** [comment]
The linked onedrive folder seems to be empty.

**Comment by leideniyifan** [comment]
I dragged my .exe to pyinstxtractor.py and it worked,maybe you can try it?

**Comment by Godisgracious1031** [comment]
https://1drv.ms/f/s!AploExad608_h4NRGENZJzB7D0ipjg?e=RkuBU6

**Comment by Godisgracious1031** [comment]
there should be two exe's in that folder. Kindly assist. Thanks.

**Comment by extremecoders-re** [comment]
Use the web tool to extract if you've trouble setting up the correct version of Python viz. 3.12.
This extracts both of the exe's successfully.

https://pyinstxtractor-web.netlify.app/

**Comment by Godisgracious1031** [comment]
Okay, how do I get it into a py file? Thanks

**Comment by Godisgracious1031** [comment]
I am quite confused, I tried a lot of tools and they don't work. Also, now the exe won't help as it seems there is a virus. May I ask where to get a good exe converter? I think maybe I should redo my python and do another way. Thanks

**Comment by Godisgracious1031** [comment]
I see, but how do I use it?

**Comment by Godisgracious1031** [comment]
C:\>./pycdc C:\Users\Godis\Downloads\Genesis 1 Quiz - AKJV.exe_extracted\Questions for Genesis 1.pyc
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by extremecoders-re** [comment]
You have to compile pycdc from source code. I also have a repository that provides precompiled pycdc.

Download **pycdc.exe** from https://github.com/extremecoders-re/decompyle-builds/releases/tag/build-20-Jan-2024-2da061f.

Then run as
```
C:\> pycdc.exe "C:\Users\Godis\Downloads\Genesis 1 Quiz - AKJV.exe_extracted\Questions for Genesis 1.pyc"
```

**Comment by Godisgracious1031** [comment]
C:\Users\Godis>C:\> pycdc.exe "C:\Users\Godis\Downloads\Genesis 1 Quiz - AKJV.exe_extracted\Questions for Genesis 1.pyc"
'C:\' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

**Comment by extremecoders-re** [comment]
Don't write `C:` at the front.

Just write or paste the following at the command prompt.
```
pycdc.exe "C:\Users\Godis\Downloads\Genesis 1 Quiz - AKJV.exe_extracted\Questions for Genesis 1.pyc"
```

**Comment by Godisgracious1031** [comment]
Thanks very much, I was able to solve it! God bless :)
