### ISSUE TITLE
No pyc file generated

### ISSUE THREAD

**Issue by Yurains** [extremecoders-re/pyinstxtractor#89]
Hello, I am currently attempting to reverse engineer the executable file of DragGAN, which is a combined version created by someone else. However, I encountered an issue where it seems that it did not generate .pyc files. Some users suggested it might be due to the Python version, recommending replacing struct, but I found that both options are the same. Could it be that Python 3.10 is not supported? If so, what should I do? Here is the link to my executable file.
![螢幕擷取畫面 2024-02-11 181603](https://github.com/extremecoders-re/pyinstxtractor/assets/114134476/804c298e-aeec-4c97-b66a-7247e0461d6e)
![螢幕擷取畫面 2024-02-11 182547](https://github.com/extremecoders-re/pyinstxtractor/assets/114134476/aaf5cac8-31ad-46ba-83e2-d34bc3506f5c)

https://drive.google.com/file/d/1NrXk6C_C-VN7vESLrjYg0kXxjdbT_bJk/view?usp=drive_link

**Comment by extremecoders-re** [comment]
You've to run pyinstxtractor.py using Python 3.10 - the same version used to build the executable. Also you seem to be using an old version of pyinstxtractor - not the one here. Otherwise pyinstxtractor works just fine on your exe.

**Comment by Yurains** [comment]
Thank you, I'll try it out and wish you a happy new year!
