### ISSUE TITLE
Unable to extract pyc files

### ISSUE THREAD

**Issue by Sud0xD** [extremecoders-re/pyinstxtractor#9]
Unable to extract pyc files for malware MD5: bbf630ca23976ddf8a561ccdb477c73d.
Seems like current script is not finding pyinstaller magic number which is there in file (one byte before in 2.1 offset). I tried to manually change the offset in the script but it is crashing in later code. Can you please check and confirm whether this is due to structure change or malware trick to bypass extraction of files.
Thanks in advance :)

**Comment by extremecoders-re** [comment]
The malware authors have added an extra null byte at the end. Removing that is enough, No change to the script is needed. :) 

```
$ python pyinstxtractor.py micro-fixed.bin
[+] Processing micro-fixed.bin
[+] Pyinstaller version: 2.1+
[+] Python version: 34
[+] Length of package: 22533241 bytes
[+] Found 107 files in CArchive
[+] Beginning extraction...please standby
[+] Possible entry point: pyiboot01_bootstrap.pyc
[+] Possible entry point: pyi_rth_win32comgenpy.pyc
[+] Possible entry point: pyi_rth_multiprocessing.pyc
[+] Possible entry point: pyi_rth_pkgres.pyc
[+] Possible entry point: Fingerprintcredential.pyc
[+] Found 890 files in PYZ archive
[+] Successfully extracted pyinstaller archive: micro-fixed.bin
```
