### ISSUE TITLE
is there anyway to pack extract folder to exe again ?

### ISSUE THREAD

**Issue by ericheshenghao** [extremecoders-re/pyinstxtractor#91]
i extract the file and simply modify the entry file, but i found no way to repack it to a exe, is there anyway to repack the exe again, please help 😢
finally thanks for all the work done in pyinstxtractor, this is an amazing tool.

**Comment by extremecoders-re** [comment]
Repack hasn't been implemented yet. Meanwhile you can try this tool https://github.com/in1nit1t/pyipx
