### ISSUE TITLE
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by kenikFJ** [extremecoders-re/pyinstxtractor#96]
FILE: https://gofile.io/d/CKep0X
help me please

**Comment by extremecoders-re** [comment]
This uses a modified pyinstaller with a custom magic. Also uses modified logic and generates the AES encryption key at runtime.

The following pyinstxtractor-ng script can extract it: https://paste.ee/p/I0vyU
Be sure to instasll the [dependencies](https://github.com/pyinstxtractor/pyinstxtractor-ng/blob/main/requirements.txt) first before running.

**Comment by kenikFJ** [comment]
**Thank you so much!!!**

If it's not too much trouble, can you explain how you figured it out? Just through the dump? I saw the last issue (https://github.com/extremecoders-re/pyinstxtractor/issues/92) and didn't understand where you get the magic from. I didn't find it at the end of the file

**Comment by kenikFJ** [comment]
![image](https://github.com/user-attachments/assets/55649514-5cd1-4fb4-b2aa-a2640db46c5e)
And is it possible to retrieve the contents of the utils folder?

**Comment by extremecoders-re** [comment]
> If it's not too much trouble, can you explain how you figured it out? Just through the dump? I saw the last issue (#92) and didn't understand where you get the magic from. I didn't find it at the end of the file

The magic of a standard pyinstaller executable is `4D 45 49 0C 0B 0A 0B 0E`. You can search For these bytes using a hex editor in a pyinstaller executable to know the location. It will be at the end of the file. In this particular file, if you check the same location you would find it is different. That way can get the modified magic `54 4C 52 0C 09 0D 0C 0B`. Check the screenshot.

![image](https://github.com/user-attachments/assets/5093d72e-0b5d-4e32-bfbc-f13c8036607a)

**Comment by 999scarecrxws** [comment]
> This uses a modified pyinstaller with a custom magic. Also uses modified logic and generates the AES encryption key at runtime.
> 
> The following pyinstxtractor-ng script can extract it: https://paste.ee/p/I0vyU Be sure to instasll the [dependencies](https://github.com/pyinstxtractor/pyinstxtractor-ng/blob/main/requirements.txt) first before running.

can u reupload this please?
